name: Maven Build CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    uses: phaneendra-bangari/GitHubActionsCentral/.github/workflows/common_maven_build.yml@main
  deploy:
    uses: phaneendra-bangari/GitHubActionsCentral/.github/workflows/common_maven_deploy.yml@main
