name: Maven Build CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    uses: phaneendra-bangari/GitHubActionsCentral/.github/workflows/common_maven_build.yml@main
  deploy:
    needs: build
    uses: phaneendra-bangari/GitHubActionsCentral/.github/workflows/common_maven_deploy.yml@main
    secrets:
       host: ${{ secrets.DC_HOST }}
       user: ${{ secrets.DC_USER }}
       password: ${{ secrets.DC_KEY }}
